server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BruceRodrigues/config-repo
  application:
    name: config
  security:
    user:
      name: config
      password: secret