CREATE DATABASE IF NOT EXISTS USUARIO;
USE USUARIO;
CREATE TABLE USUARIO.TB_USUARIO
(
  CO_SEQ_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
  NO_USUARIO VARCHAR(255) NOT NULL
);
ALTER TABLE USUARIO.TB_USUARIO COMMENT = 'Informações do Usuário';