CREATE DATABASE IF NOT EXISTS USUARIO;
USE USUARIO;

# --TB_PERFIL
CREATE TABLE USUARIO.TB_PERFIL
(
    CO_PERFIL int PRIMARY KEY,
    DS_PERFIL VARCHAR(255) NOT NULL,
    DS_ICON VARCHAR(255) NOT NULL
);
ALTER TABLE TB_PERFIL COMMENT = 'Tabela domínio com os possíveis perfis';

INSERT INTO USUARIO.TB_PERFIL(CO_PERFIL, DS_PERFIL, DS_ICON) VALUES (0, 'Leito', 'face');
INSERT INTO USUARIO.TB_PERFIL(CO_PERFIL, DS_PERFIL, DS_ICON) VALUES (1, 'Técnico', 'assignment_ind');
INSERT INTO USUARIO.TB_PERFIL(CO_PERFIL, DS_PERFIL, DS_ICON) VALUES (2, 'Gestor Federal', 'android');

# --TB_ENDERECO
CREATE TABLE USUARIO.TB_ENDERECO
(
    CO_SEQ_ENDERECO int PRIMARY KEY AUTO_INCREMENT,
    CO_MUNICIPIO int NOT NULL,
    NO_MUNICIPIO VARCHAR(255),
    NU_CEP VARCHAR(8) NOT NULL,
    SG_UF VARCHAR(2),
    DS_LOGRADOURO VARCHAR(255),
    DS_COMPLEMENTO VARCHAR(255),
    DS_BAIRRO VARCHAR(255),
    DS_NUMERO VARCHAR(10)
);
CREATE INDEX IN_ENDERECO_UF ON USUARIO.TB_ENDERECO (SG_UF);
CREATE INDEX IN_ENDERECO_MUNICIPIO ON USUARIO.TB_ENDERECO (CO_MUNICIPIO);
ALTER TABLE USUARIO.TB_ENDERECO COMMENT = 'Informações de endereço';

# --TB_USUARIO
CREATE TABLE USUARIO.TB_USUARIO
(
    CO_SEQ_USUARIO int PRIMARY KEY AUTO_INCREMENT,
    NO_USUARIO VARCHAR(255) NOT NULL,
    DS_SENHA VARCHAR(255) NOT NULL,
    CO_ENDERECO int NOT NULL,
    DS_USUARIO VARCHAR(11) NOT NULL,
    CONSTRAINT FK_ENDERECO_USUARIO FOREIGN KEY (CO_ENDERECO) REFERENCES TB_ENDERECO (CO_SEQ_ENDERECO)
);
ALTER TABLE USUARIO.TB_USUARIO COMMENT = 'Informações do Usuário';

# --RL_PERFIL_USUARIO
CREATE TABLE USUARIO.RL_PERFIL_USUARIO (
    CO_USUARIO INT,
    CO_PERFIL INT,
    CONSTRAINT FK_USUARIO_PERFILUSUARIO FOREIGN KEY (CO_USUARIO) REFERENCES  TB_USUARIO (CO_SEQ_USUARIO),
    CONSTRAINT FK_PERFIL_PERFILUSUARIO FOREIGN KEY (CO_PERFIL) REFERENCES  TB_PERFIL (CO_PERFIL)
);
ALTER TABLE USUARIO.RL_PERFIL_USUARIO COMMENT = 'Relação usuário-perfil';


