spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8082